version: '3.7'

networks:
  car-mechanic:

services:
  mechanic:
    container_name: mechanic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - car-mechanic
  mysql-service:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mechanic
      MYSQL_ROOT_PASSWORD: mechanic95
      MYSQL_USER: mechanic
      MYSQL_PASSWORD: mechanic95
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/mechanic
    networks:
      - car-mechanic

